# packages/configurator/Taskfile.yml
version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - bun x remix vite:build

  dev:
    desc: Run in development mode
    cmds:
      - bun x remix vite:dev

  serve:
    desc: Run in development mode
    cmds:
      # Can't run with bun yet, see https://github.com/remix-run/remix/discussions/7413
      - npx remix-serve build/server/index.js

  lint:
    desc: Run ESLint
    cmds:
      - bun x eslint .

  test:
    desc: Run ESLint
    cmds:
      - echo "No tests :/"

  type-check:
    desc: Run TypeScript type checking
    cmds:
      - bun x tsc --noEmit
