# packages/configurator/Taskfile.yml
version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - bun x remix vite:build

  dev:
    desc: Run in development mode
    cmds:
      - bun x remix vite:dev

  serve:
    desc: Run in development mode
    cmds:
      # Can't run with bun yet, see https://github.com/remix-run/remix/discussions/7413
      - npx remix-serve build/server/index.js

  prettier-check:
    desc: Check if files are formatted with Prettier
    cmds:
      - bun x prettier --check *.json *.ts app/**/*.ts

  eslint-check:
    desc: Run ESLint
    cmds:
      - bun x eslint --ext .ts,.tsx,.js,.jsx

  lint:
    desc: Lint code
    cmds:
      - task: eslint-check
      - task: prettier-check

  test:
    desc: Run unit tests
    cmds:
      - bun x vitest --run

  type-check:
    desc: Run TypeScript type checking
    cmds:
      - bun x tsc --noEmit
