# packages/configurator/Taskfile.yml
version: '3'

includes:
  base-bun:
    taskfile: ../base-bun/Taskfile.yaml

tasks:
  build:
    desc: Build the project
    cmds:
      - bun x remix vite:build

  dev:
    desc: Run in development mode
    cmds:
      - bun x remix vite:dev

  serve:
    desc: Run in development mode
    cmds:
      - bun x remix-serve build/server/index.js

  eslint-check:
    desc: Run ESLint
    cmds:
      - bun x eslint --ext .ts,.tsx,.js,.jsx

  lint:
    desc: Lint code
    cmds:
      - task: eslint-check
      - task: base-bun:tsc-check
      - task: base-bun:prettier-check

  test:
    desc: Run tests
    cmds:
      - task: base-bun:test
