name = "ruuvipuserrin-configurator"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-07-19"
upload_source_maps = true

[site]
bucket = "./public"

[build]
command = "npx nx build"
