# Root Taskfile.yml
version: '3'

dotenv:
  - .env.local
  - .env

includes:
  archive:
    taskfile: packages/archive/Taskfile.yml
    dir: packages/archive
  common-archive-client:
    taskfile: packages/common-archive-client/Taskfile.yml
    dir: packages/common-archive-client
  common-data:
    taskfile: packages/common-data/Taskfile.yml
    dir: packages/common-data
  common-postgres:
    taskfile: packages/common-postgres/Taskfile.yml
    dir: packages/common-postgres
  configurator:
    taskfile: packages/configurator/Taskfile.yml
    dir: packages/configurator
  gatherer-stdin:
    taskfile: packages/gatherer-stdin/Taskfile.yml
    dir: packages/gatherer-stdin
  gatherer-http:
    taskfile: packages/gatherer-http/Taskfile.yml
    dir: packages/gatherer-http
  infra-postgres:
    taskfile: packages/infra-postgres/Taskfile.yml
    dir: packages/infra-postgres
  infra-redis:
    taskfile: packages/infra-redis/Taskfile.yml
    dir: packages/infra-redis
  listener:
    taskfile: packages/listener/Taskfile.yml
    dir: packages/listener
  publisher:
    taskfile: packages/publisher/Taskfile.yml
    dir: packages/publisher

tasks:
  run_parallel:
    desc: Run specified tasks in parallel
    vars:
      TASKS: '{{.TASKS | default ""}}'
    cmds:
      - ./run_parallel_task.sh {{.TASKS}}

  start-gateway:
    desc: Start gateway services in parallel
    cmds:
      - task: run_parallel
        vars:
          TASKS: >
            gatherer-stdin:start
            gatherer-http:start
            publisher:start

  dev-infra:
    desc: Start development infrastructure in parallel
    cmds:
      - task: run_parallel
        vars:
          TASKS: >
            infra-postgres:dev
            infra-redis:dev

  dev-apps:
    desc: Start development applications in parallel
    cmds:
      - task: run_parallel
        vars:
          TASKS: >
            archive:dev
            configurator:dev
            gatherer-http:dev
            gatherer-stdin:dev
            publisher:dev
