# packages/gatherer-stdin/Taskfile.yml
version: '3'

includes:
  base-bun:
    taskfile: ../base-bun/Taskfile.yaml
    flatten: true

tasks:
  dev-listener:
    desc: Run the mock listener
    cmds:
      - bun --no-install-node-api listener-mock.ts --measurementName=ruuvipuserrin-mock --pollingInterval=1000

  dev-app:
    desc: Run the application in development mode
    cmds:
      - bun --no-install-node-api index.ts --measurementName=ruuvipuserrin-mock --pollingInterval=15000

  dev:
    desc: Run in development mode
    cmds:
      # TODO, this doesn't work currently in MacOS due to Bun issue with stdin https://github.com/oven-sh/bun/issues/10080
      - task dev-listener --silent | task dev-app

  start:
    desc: Start the application
    cmds:
      - echo "Start gathering to $REDIS_HOST:$REDIS_PORT"
      - bun index.ts --measurementName=$INFLUXDB_MEASUREMENT --pollingInterval=15000
