# packages/gatherer-stdin/Taskfile.yml
version: '3'

includes:
  base-bun:
    taskfile: ../base-bun/Taskfile.yaml
    flatten: true
    
tasks:
  dev:
    desc: Run in development mode
    cmds:
      - bun listener-mock.ts --measurementName=ruuvipuserrin-mock --pollingInterval=1000 | bun index.ts --measurementName=ruuvipuserrin-mock --pollingInterval=1000

  start:
    desc: Start the application
    cmds:
      - echo "Start gathering to $REDIS_HOST:$REDIS_PORT"
      - bun index.ts --measurementName=$INFLUXDB_MEASUREMENT --pollingInterval=15000
