apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruuvipuserrin-archive

  labels:
    app: ruuvipuserrin-archive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruuvipuserrin-archive
  template:
    metadata:
      labels:
        app: ruuvipuserrin-archive
    spec:
      imagePullSecrets:
        - name: github-registry-secret
      containers:
        - name: ruuvipuserrin-archive
          image: ghcr.io/unkhz/ruuvipuserrin-archive:latest
          env:
            - name: PG_HOST
              value: ruuvipuserrin
            - name: PG_PORT
              value: '5432'
            - name: PG_DB
              value: 'ruuvi'
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: archive.ruuvipuserrin.credentials.postgresql.acid.zalan.do
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: archive.ruuvipuserrin.credentials.postgresql.acid.zalan.do
                  key: password
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '1024Mi'
              cpu: '400m'
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 300
            timeoutSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: ruuvipuserrin-archive-service

  annotations:
    external-dns.alpha.kubernetes.io/hostname: ruuvipuserrin-archive.khz.fi

spec:
  selector:
    app: ruuvipuserrin-archive
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ruuvipuserrin-archive-ingress

  annotations:
    kubernetes.io/ingress.class: 'traefik'
    cert-manager.io/cluster-issuer: 'letsencrypt-prod'
spec:
  rules:
    - host: ruuvipuserrin-archive.khz.fi
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ruuvipuserrin-archive-service
                port:
                  number: 80
  tls:
    - hosts:
        - ruuvipuserrin-archive.khz.fi
      secretName: ruuvipuserrin-archive-tls
