apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deployment.yaml
  - postgresql.yaml
  - backup-secret.sealed.yaml
images:
  - name: ghcr.io/unkhz/ruuvipuserrin-archive
    newTag: fb0198511bf7cf7dffb12330ce2a33de6d912f3f
