apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deployment.yaml
  - postgresql.yaml
  - backup-secret.sealed.yaml
images:
  - name: ghcr.io/unkhz/ruuvipuserrin-archive
    newTag: 9de78e413b95cbe326235db67db52c29cd93d9a6
