apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deployment.yaml
  - postgresql.yaml
  - backup-secret.sealed.yaml
images:
  - name: ghcr.io/unkhz/ruuvipuserrin-archive
    newTag: ee25cd67a84c05004017bdb7c70aa65385c24ad4
