# packages/gatherer-http/Taskfile.yml
version: '3'

includes:
  base-bun:
    taskfile: ../base-bun/Taskfile.yaml
    flatten: true

tasks:
  start:
    desc: Start the application
    cmds:
      - echo "Start gathering to $REDIS_HOST:$REDIS_PORT"
      - bun index.ts --measurementName=ruuvipuserrin-rH48dag03 --pollingInterval=15000

  dev:
    desc: Run in development mode
    cmds:
      - bun --watch index.ts --measurementName=ruuvipuserrin-rH48dag03 --pollingInterval=15000
