# packages/gatherer-http/Taskfile.yml
version: '3'

tasks:
  prettier-write:
    desc: Run Prettier and format files
    cmds:
      - bun prettier --write *.json *.ts lib/**/*.ts

  prettier-check:
    desc: Check if files are formatted with Prettier
    cmds:
      - bun prettier --check *.json *.ts lib/**/*.ts

  test-unit:
    desc: Run unit tests
    cmds:
      - bun test

  lint:
    desc: Run linter (Prettier check)
    cmds:
      - task: prettier-check

  test:
    desc: Run all tests
    cmds:
      - task: test-unit

  build:
    desc: Build the project
    cmds:
      - bun index.ts --tsconfig-override tsconfig.build.json

  start:
    desc: Start the application
    cmds:
      - echo "Start gathering to $REDIS_HOST:$REDIS_PORT"
      - bun index.ts --measurementName=ruuvipuserrin-rH48dag03 --pollingInterval=15000

  dev:
    desc: Run in development mode
    cmds:
      - bun --watch index.ts --measurementName=ruuvipuserrin-rH48dag03 --pollingInterval=15000
