# packages/archive/Taskfile.yml
version: '3'

includes:
  base-bun:
    taskfile: ../base-bun/Taskfile.yaml
    flatten: true

tasks:
  dev:
    desc: Run in development mode
    cmds:
      - bun --watch index.ts

  start:
    desc: Start the application
    cmds:
      - bun x node dist/index.js

  docker:run:
    desc: Run the application in Docker
    cmds:
      - docker run --name=ruuvipuserrin-archive --env-file=../../.env.local --rm -p 4000:4000 ruuvipuserrin/archive

  docker:stop:
    desc: Stop the Docker container
    cmds:
      - docker stop ruuvipuserrin-archive
