# packages/common-data/Taskfile.yml
version: '3'

includes:
    base-bun:
      taskfile: ../base-bun/Taskfile.yaml
      flatten: true
      
tasks:
  setup:
    desc: Install system dependencies
    cmds:
      - sudo apt install protobuf-compiler

  protoc-ruuvi:
    desc: Generate TypeScript from Ruuvi proto file
    cmds:
      - bun x protoc --plugin=$(npm bin)/protoc-gen-ts_proto --ts_proto_opt=snakeToCamel=false --ts_proto_out=. lib/formats/ruuvi.proto

  protoc:
    desc: Generate all protobuf files and format
    cmds:
      - task: protoc-ruuvi
      - task: prettier-write
