# packages/publisher/Taskfile.yml
version: '3'

includes:
    base-bun:
      taskfile: ../base-bun/Taskfile.yaml
      flatten: true
      
tasks:
  dev:
    desc: Run in development mode
    cmds:
      - bun index.ts --measurementName=ruuvipuserrin-mock --pollingInterval=1000

  start:
    desc: Start the application
    cmds:
      - echo "Start publishing to $ARCHIVE_API_HOST"
      - bun index.ts --measurementName=ruuvipuserrin-rH48dag03 --pollingInterval=15000
