# packages/publisher/Taskfile.yml
version: '3'

tasks:
  prettier-write:
    desc: Run Prettier and format files
    cmds:
      - bun x prettier --write *.json *.ts lib/**/*.ts

  prettier-check:
    desc: Check if files are formatted with Prettier
    cmds:
      - bun x prettier --check *.json *.ts lib/**/*.ts

  test-unit:
    desc: Run unit tests
    cmds:
      - bun x jest --no-cache --ci

  lint:
    desc: Run linter (Prettier check)
    deps:
      - prettier-check

  test:
    desc: Run all tests
    deps:
      - test-unit

  build:
    desc: Build the project
    cmds:
      - bun index.ts --tsconfig-override tsconfig.build.json

  dev:
    desc: Run in development mode
    cmds:
      - bun index.ts --measurementName=ruuvipuserrin-mock --pollingInterval=1000

  start:
    desc: Start the application
    cmds:
      - echo "Start publishing to $ARCHIVE_API_HOST"
      - bun index.ts --measurementName=ruuvipuserrin-rH48dag03 --pollingInterval=15000
