apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deployment.yaml
images:
  - name: ghcr.io/unkhz/ruuvipuserrin-configurator
    newTag: 54c75f74f2154d973c7b602a9cc1d5f4310e7ac0
