apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deployment.yaml
images:
  - name: ghcr.io/unkhz/ruuvipuserrin-configurator
    newTag: 4f50d59ef7273039ba6245407d38bce4b8b98ba8
