apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - deployment.yaml
images:
  - name: ghcr.io/unkhz/ruuvipuserrin-configurator
    newTag: 216858d5095a92ef77fa5b0108bf0a0b1382430d
