version: '3'

tasks:
  setcap:
    cmds:
      - sudo setcap 'cap_net_raw,cap_net_admin+eip' ./dist/bin/ruuvitag-listener

  cargo-install:
    cmds:
      - cargo install ruuvitag-listener --locked --root ./dist --release -j 1
    env:
      RUSTFLAGS: "-C opt-level=3 -C codegen-units=1 -C lto=fat"

  setup:
    cmds:
      - task: cargo-install
      - task: setcap

  start:
    cmds:
      - ./dist/bin/ruuvitag-listener --influxdb-measurement=$INFLUXDB_MEASUREMENT
