version: '3'

services:
  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    # use REDIS_ARGS for redis-stack-server instead of command arguments
    environment:
      - REDIS_ARGS=--save 1200 32