# packages/common-postgres/Taskfile.yml
version: '3'

includes:
  base-bun:
    taskfile: ../base-bun/Taskfile.yaml
    flatten: true

tasks:
  migrate-one-up:
    desc: Run one migration up for a specific tenant
    cmds:
      - bun ./manual-migrate.ts --tenantId $TENANT_ID --job up

  migrate-one-down:
    desc: Run one migration down for a specific tenant
    cmds:
      - bun ./manual-migrate.ts --tenantId $TENANT_ID --job down

  migrate-to-latest:
    desc: Migrate to the latest version for a specific tenant
    cmds:
      - bun ./manual-migrate.ts --tenantId $TENANT_ID --job latest
