# packages/common-archive-client/Taskfile.yml
version: '3'

tasks:
  prettier-write:
    desc: Run Prettier and format files
    cmds:
      - bun x prettier --write *.json *.ts lib/**/*.ts

  prettier-check:
    desc: Check if files are formatted with Prettier
    cmds:
      - bun x prettier --check *.json *.ts lib/**/*.ts

  test-unit:
    desc: Run unit tests
    cmds:
      - bun x jest --no-cache --ci

  lint:
    desc: Run linter (Prettier check)
    cmds:
      - task: prettier-check

  test:
    desc: Run all tests
    cmds:
      - task: test-unit

  build:
    desc: Build the project
    cmds:
      - bun build --target=bun --outfile=dist/index.js index.ts
