{
 "title": "All tags",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  temperature as _value,\n  COALESCE(name, shortname, source::text) AS name\nFROM\n  ruuvi_measurement_1m\nWHERE\n  $__timeFilter(time) \nORDER BY time"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  humidity as _value,\n  COALESCE(name, shortname, source::text) AS name\nFROM\n  ruuvi_measurement_1m\nWHERE\n  $__timeFilter(time) \nORDER BY time"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  pressure as _value,\n  COALESCE(name, shortname, source::text) AS name\nFROM\n  ruuvi_measurement_1m\nWHERE\n  $__timeFilter(time) \nORDER BY time"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "mvolt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('15 minutes', time) AS time,\n  avg(battery_potential::real / 1000) as _value,\n  source AS name\nFROM\n  ruuvi_health\nWHERE\n  $__timeFilter(time)\nGROUP BY source, time\nORDER BY time"
    }
   ]
  }
 ]
}