name: Master
on:
  push:
    branches: ['master']

jobs:
  test-ts:
    if: ${{ ! endsWith(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package:
          - archive
          - common-archive-client
          - common-data
          - common-postgres
          - configurator
          - gatherer-http
          - gatherer-stdin
          - publisher

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: arduino/setup-task@v2
        with:
          version: 3.42.1
      # Update lockfile here until renovate can update it
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: '.bun-version'
      - run: bun install
      - run: task ${{ matrix.package }}:lint
      - run: task ${{ matrix.package }}:test

  build-base-images:
    if: ${{ ! endsWith(github.event.head_commit.message, '[skip ci]') }}
    needs: test-ts
    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        args:
          - context: .
            image: ghcr.io/unkhz/ruuvipuserrin-base-bun

    uses: ./.github/workflows/build-package.yml
    with:
      context: ${{ matrix.args.context }}
      image: ${{ matrix.args.image }}

  build-package-images:
    if: ${{ ! endsWith(github.event.head_commit.message, '[skip ci]') }}
    needs: build-base-images
    permissions:
      contents: write
      packages: write

    strategy:
      matrix:
        args:
          - context: ./packages/archive
            image: ghcr.io/unkhz/ruuvipuserrin-archive
          - context: ./packages/configurator
            image: ghcr.io/unkhz/ruuvipuserrin-configurator

    uses: ./.github/workflows/build-package.yml
    with:
      context: ${{ matrix.args.context }}
      image: ${{ matrix.args.image }}

  update-version-tags:
    if: ${{ ! endsWith(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest
    needs: build-package-images
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install yq
        uses: mikefarah/yq@master
        with:
          cmd: yq --version

      # Update lockfile here until renovate can update it
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: '.bun-version'
      - run: bun install

      - name: Update version tags
        run: |
          function update_version_tag() {
            file=$1
            yq e '.images[0].newTag = "${{ github.sha }}"' -i $file
            git add $file
          }

          # Update lockfile here until renovate can update it
          git add bun.lock

          update_version_tag ./packages/base-bun/.khz-k3s/kustomization.yaml
          update_version_tag ./packages/archive/.khz-k3s/kustomization.yaml
          update_version_tag ./packages/configurator/.khz-k3s/kustomization.yaml

          git config --global user.email "juhani.pelli@gmail.com"
          git config --global user.name "Juhani Pelli"
          git commit -m "Deploy ${{ github.sha }} [skip ci]"
          git push origin ${{ github.event.repository.default_branch }}
